# Generated by Django 5.0.2 on 2024-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Location', models.CharField(choices=[('CA', 'Canada'), ('US', 'United States'), ('MX', 'Mexico'), ('UK', 'United Kingdom')], max_length=64)),
                ('hourly_rate_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.TextField(max_length=4096)),
                ('skills', models.ManyToManyField(to='artish_freelancers.skill')),
                ('social_links', models.ManyToManyField(to='artish_freelancers.sociallink')),
                ('tools', models.ManyToManyField(to='artish_freelancers.tool')),
            ],
        ),
    ]
